### ISSUE TITLE
Saving player: false SPAM

### ISSUE THREAD

**Issue by Drew-Chase** [LimeAppleBoat/ThonkUtil#15] opened 2022-04-18 00:27 UTC
Server spams this message for every player every 5 seconds/autosave

![image](https://user-images.githubusercontent.com/5598099/163737745-881ad923-b50f-498b-9524-d4154b3365ec.png)

**Comment by Jab125** [comment] 2022-04-18 00:51
Duplicate of #14

**Closed as completed** 2022-04-18 00:52 UTC
