### ISSUE TITLE
thonkutil:universal_packet

### ISSUE THREAD

**Issue by BoonyCat** [LimeAppleBoat/ThonkUtil#28] opened 2022-07-08 13:00 UTC
Error when connecting to Fabric server:

[14:55:37] [Netty Server IO #2/INFO]: [STDERR]: Client did not understand response query message with channel name **thonkutil:universal_packet**
[14:55:37] [Netty Server IO #2/INFO]: Disconnecting com.mojang.authlib.GameProfile@6d6e468d[id=14c24a36-9ce3-4216-bb4f-a07399e4b5ee,name=BoonyCat,properties={textures=[com.mojang.authlib.properties.Property@7174ea4e]},legacy=false] (/127.0.0.1:58856):
[14:55:37] [Server thread/INFO]: com.mojang.authlib.GameProfile@6d6e468d[id=14c24a36-9ce3-4216-bb4f-a07399e4b5ee,name=BoonyCat,properties={textures=[com.mojang.authlib.properties.Property@7174ea4e]},legacy=false] (/127.0.0.1:58856) lost connection:

**Comment by Jab125** [comment] 2022-07-09 02:02
Duplicate of #25

**Closed as completed by Jab125** 2022-07-09 02:02 UTC
