### ISSUE TITLE
1.19 Crash

### ISSUE THREAD

**Issue by Tenuuu** [LimeAppleBoat/ThonkUtil#20] opened 2022-06-12 23:20 UTC
Title. Not sure what is causing the crash as it doesn't give much information in the logs.
https://gist.github.com/Tenuuu/f5e1b6c7b3b425054cb916ffc8081f4e

**Comment by Jab125** [comment] 2022-06-12 23:52
Duplicate of #19

**Closed as completed** 2022-06-12 23:52 UTC
